### ISSUE TITLE
The "open" command is not a native powershell function and doesn't work on Windows machines.

### ISSUE THREAD

**Issue by cluedindev** [CluedIn-io/Home#14]
In the documentation we talk about an "open http://app*****. When I run this I get an error and this should therefor either not be suggested as the way to open the browser or alternatives should be advised. 

open: The term 'open' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by Kieranties** [comment]
This is incorrect documentation and has already been removed for 3.2.4
